### ISSUE TITLE
Question Rather Than Issue

### ISSUE THREAD

**Issue by ffreality** [Ysgrathe/SQLiteGameDb#2]
I exposed Epic's SQLite to blueprints a while ago but it crashes when I use multiple read request.
https://github.com/FF-Projects-UE/DB_Connections/issues/1

Is this SQLite's problem ? Do you have same problem ? And does it support Android ?

If they I can use multiple read and supports Android, I will archive mine.

**Comment by Ysgrathe** [comment]
Epic's code wont allow you to do multiple connections to the same SQLite database.

Does SQLite support it? YES.
Do Epic allow it? NO

The reason is because to allow multiple concurrent access to the same SQLite database, SQLite itself needs to use certain features which are not available on all the platforms which Unreal can be deployed to.

Rather than allow you to decide for yourself if you are targeting a supported platform, Epic simply decided to avoid the entire thing, and just throw an exception. So using Epic's SQLite library you cannot do it.

Using my library, you also cannot do it - because although my library uses it's own SQLite code, it is basically just a clone of Epic's with an updated SQLite C library.


HOWEVER
Whenever anyone asks me about this, it is usually because they want to structure their projects in a manner which they don't actually require to achieve what they need. Generally speaking, a single SQLite connection is all you would ever really need. Yes, there are edge case situations, where people are trying to use a SQLite database as a for of 'cross process communication' or whatever, but within a single Unreal application, there is simply no reason most of the time to want to do it.

If you want to talk more about this, jump onto the discord server: https://discord.gg/nFPJwmeU
I rarely check github.
