### ISSUE TITLE
Plugin does not build

### ISSUE THREAD

**Issue by suvidh** [Ysgrathe/SQLiteGameDb#5]
The plugin does not build for 4.26, I know that the plugin has only been tested for 5.2 and 5.1. I wanted to see if it is possible to make it work for 4.26.2

**Comment by Ysgrathe** [comment]
Yes it is, in fact a friend of mine is using it in just such a situation.
You will need to make some very minor changes to the code for it to compile however.
These changes are not because of UE framework differences, but rather because of the change in C++ versions supported by the newer UE.

If I recall correctly, there are 2 places code must be changed, and there are both IF statements where a variable is declared inside the if statement brackets.

Simply move the variable outside, before the IF statement and things should be able to compile for UE 4.26/27
