### ISSUE TITLE
Type is null if the first row has null value

### ISSUE THREAD

**Issue by etulossolute** [Ysgrathe/SQLiteGameDb#6]
Hello!

Thanks for the plugin, it's been super helpful. However, I think I've come across a bug. Let me explain.

When a table has a null value on the first row, the plugin assign null type to that column, but if it has a value, and the others rows have or not, it correctly assign the type.

Here is an example. I have the following table:
| id (INT) | option (STRING) | order (INT) |
|----------|-----------------|-------------|
| 1        | (NULL)          | 1           |
| 2        | (NULL)          | 2           |
| 3        | A               | 1           |
| 4        | A               | 2           |
| 5        | (NULL)          | 3           |

When I try to get the option value like this.

`Result = Statement->ExecuteSelect();`
`	for (FQueryResultRow row : Result.Rows){`
`		for (FQueryResultField field : row.Fields){`
`			if (field.ColName == "option")`
`                           step.option = field.StrVal;`

`LogTemp: Warning: Option: `
`LogTemp: Warning: Option: `
`LogTemp: Warning: Option: `
`LogTemp: Warning: Option: `
`LogTemp: Warning: Option: `

field.StrVal is always empty because field.type is null. But if I assign a value on the first row.

| id (INT) | option (STRING) | order (INT) |
|----------|-----------------|-------------|
| 1        |A         | 1           |
| 2        | (NULL)          | 2           |
| 3        | A               | 1           |
| 4        | A               | 2           |
| 5        | (NULL)          | 3           |

field.StrVal is empty when the value is null (obviously) but it is not on the others. And field.type is FString.

`LogTemp: Warning: Option: A`
`LogTemp: Warning: Option: `
`LogTemp: Warning: Option: A`
`LogTemp: Warning: Option: A`
`LogTemp: Warning: Option: `

Maybe I'm missing something but I don't know why this is happening.

Thanks in advance!

**Comment by Ysgrathe** [comment]
Well, you and I would consider that a bug... but unfortunately I don't think SQLite agrees.
Because (for better or worse) SQLite prides itself on its 'loosey-goosey' approach to data typing, which is a pretty big deviation from basically EVERY OTHER SQL database ever made.

Generally with any kind of resultset, either directly from a single table, or a synthetic one, you have 2 things; the data itself (a number of rows) and the definition that this data subscribes to.
The data rows in a proper SQL resultset cannot change datatype half way through the results - field 1, is always of whatever the type is, and NULL is obviously NOT a row type, I mean, what would be the purpose of having a database field designed to store only nulls? 
Rather NULL is a (potentially) permissible value for any other datatype.

I wrote the function in the helper plugin to get the column names and types, and then get the data (because its generally 2 separate operations) and the column data I get using the sqlite3_column_type() function of the prepared statement.
And at the time, I guess I assumed it worked like a SQL database generally does. (My bad!)

Your evidence basically suggests, that rather than working as anyone familiar with SQL would expect, the results it returns are in fact NOT related to the prepared statement as a whole, but are actually influenced by each Step() while running it.

There are a few ways to approach 'fixing' this:
- If using the newer versions of SQLite (the plugin has a fairly new version) you can use the STRICT TABLE option (required individually on EACH table!) This MIGHT make a difference to how things work/are reported (but I wouldnt guarantee it, and it would need to be tested)
- You can manually fudge any query to ensure that it never returns NULLS, or, that there is a FAKE FIRST ROW with no nulls in it. Yes I know, thats a completely crap solution, but I mention it anyway.
- I could rewrite the code to preparse the entire resultset, filling in the column type for each column, when the value isnt null, and stopping once it has a complete set of column types with non null data.

That last one sounds workable until you consider the following:
- What if all the data in a given column is null for a returned dataset? Actually quite possible with filtering, etc.
- What if, due to the 'flexible' typing in SQLite, the first column of the first row returns an INTEGER, and the first column of the second row, returns TEXT? Also quite possible with SQLite.

# OR WE FORGET ALL ABOUT 'NORMAL' SQL DATABASES...
And we just embrace the 'type fluidity' of SQLite, and I don't pre parse the columns at all, instead setting the fields of each row individually, for each row. Meaning that for a single resultset, you never really know what you are going to get until you look at it. And you cant assume anything, just because the previous row was that type.

I can make the changes for that last option, but I don't really have the time to test it right now.
As you have data which creates the error, I'm happy to commit the required changes if you want to have a go at testing them?

**Comment by etulossolute** [comment]
Hi there!
I Appreciate your detailed response. I experimented with the STRICT option, but it's basically doing the same thing.
About the first dummy row, I tried instead inserting the string "NULL" when the value is null, but like you said, it's not the best solution.
I believe the third option might be effective in my situation, because I'm not planning to use that flexibility of SQLite. If you could spare the time to provide the fix, I'd be more than happy to test it out.
Thanks!

**Comment by Ysgrathe** [comment]
Well, the change is there.
I re tested it on my base app, and it still worked (not testing your specific case though)
So let me know how it goes.

The main problem you are going to have now though, is that you will need to test every time
You could switch/case the 'type' property
or you could use the IsNull() method, something like:
FString ThisValue = ResultField.IsNull()?FString(TEXT("Nothing there!")):ResultField.StrVal;

**Comment by etulossolute** [comment]
Hello,
 
I forgot to mention that I wasn't using the latest version of the plugin. Since we're operating with UE5.1, I downloaded [this release](https://github.com/Ysgrathe/SQLiteGameDb/releases/tag/UE5.1). It appears that the most recent version is not compatible, likely due to differences in the C++. If you know how to make it compatible, that would be great. However, for now, to address this issue, I have manually modified the file with the same changes you made.
 
Good news, it worked! Now, only the rows with null values are of null type, allowing me to easily check the type or if the string is empty.
 
Thanks!

**Comment by Ysgrathe** [comment]
Glad it works for you! 😄 

There are different C++ versions supported, primarily by different compiler toolchains/coupled with different engines.
I was under the impression that C++20 was supported by UE5.0 and higher, as long as you are compiling it with something that uses C++20 (you can still use VS2019 hoever which probably isnt rocking C++20 as standard)
So perhaps, upgrade your IDE to VS2022 if you are still on VS2019 for example.

Either way, in this case the differences to the code are actually minimal, and you would find them yourself very quickly if you tried to build it.
(I have a friend using my plugin on UE4.27, and you need to change only 1 or 2 lines of code max)

In case you ever want to try it, it is just a couple of IF statements where a variable is declare INSIDE the IF parentheses as part of the statement, as opposed to having a single line declaration before the IF statement
(My IDE is Rider and it pushes such things on you!)

Was actually easy to just change those lines and rebuild
